name: metro
channels:
  - conda-forge 
dependencies:
  - python=3.9
  - altair
  - altair_saver
  - geopandas
  - pygeos
  - matplotlib
  - contextily
  - jupyterlab
  - pandas
  - tweepy
  - pyarrow
  - python-dotenv
  - requests
  - pip
  - protobuf
  - pip:
    - gtfs-realtime-bindings
    - partridge
