name: Create cancellation report

on:
  schedule:
    - cron: "33 12 * * *"
  workflow_dispatch:

jobs:
  cancellation-report:
    name: Create cancellation report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: metro

      - name: mamba list
        shell: bash -l {0}
        run: mamba list

      - name: Create report 
        shell: bash -l {0}
        run: |
          jupyter execute cancellations.ipynb
      - name: Commit back to the repo
        shell: bash -l {0}
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A cancellation-reports/ && git diff --cached --exit-code --quiet || git commit -m "Updated cancellation reports"
