name: Pull Trip Update Data

on:
  schedule:
    - cron: "33 * * * *"
  workflow_dispatch:

jobs:
  test-updates:
    name: Pull Trip Update Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: metro

      - name: mamba list
        shell: bash -l {0}
        run: mamba list

      - name: Pull RT Data 
        shell: bash -l {0}
        env:
          SWIFTLY_API_KEY: ${{ secrets.SWIFTLY_API_KEY }}
        run: |
          python trip_updates.py
      - name: Commit back to the repo
        shell: bash -l {0}
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A trip-updates/ && git diff --cached --exit-code --quiet || git commit -m "Updated trip updates"
          git push
